# Generated by Django 2.2 on 2019-05-26 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190526_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cafe',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.Cafe'),
        ),
    ]
