# Generated by Django 2.2 on 2019-05-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190526_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-start_time', '-end_time'), 'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ('-date',), 'verbose_name': 'salary', 'verbose_name_plural': 'salaries'},
        ),
    ]
