# Generated by Django 2.2 on 2019-05-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20190525_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('max_seats', models.IntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Shop')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
                'unique_together': {('shop', 'number')},
            },
        ),
    ]
