# Generated by Django 2.2 on 2019-05-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_auto_20190526_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unittype',
            options={'verbose_name': 'unit type', 'verbose_name_plural': 'unit types'},
        ),
    ]
