# Generated by Django 2.2 on 2019-05-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_auto_20190526_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='products',
            field=models.ManyToManyField(related_name='ingredients', through='cafe.ProductIngredient', to='cafe.Product'),
        ),
    ]
