# Generated by Django 2.2 on 2019-05-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_auto_20190526_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='products', through='cafe.ProductIngredient', to='cafe.Ingredient'),
        ),
    ]
