# Generated by Django 2.2 on 2019-05-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Ingredient')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='ingredients',
            field=models.ManyToManyField(related_name='shops', through='cafe.StorageState', to='cafe.Ingredient'),
        ),
    ]
