# Generated by Django 2.2 on 2019-05-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_auto_20190527_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliedIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.ManyToManyField(related_name='supplies', through='cafe.SuppliedIngredient', to='cafe.Ingredient')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Shop')),
            ],
            options={
                'verbose_name': 'supply',
                'verbose_name_plural': 'supplies',
            },
        ),
        migrations.AddField(
            model_name='suppliedingredient',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Supply'),
        ),
    ]
